"""initial_schema

Revision ID: f406ea662c6c
Revises: 
Create Date: 2026-05-09 14:38:42.097654

"""
from alembic import op
import sqlalchemy as sa


revision = 'f406ea662c6c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bid_rounds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('commodity', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('submission_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('reserve_price_enabled', sa.Boolean(), nullable=True),
    sa.Column('master_file_uploaded', sa.Boolean(), nullable=True),
    sa.Column('master_file_path', sa.String(), nullable=True),
    sa.Column('total_line_items', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bid_rounds_id'), 'bid_rounds', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('fluff_percentage', sa.Float(), nullable=True),
    sa.Column('last_bid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_rounds_participated', sa.Integer(), nullable=True),
    sa.Column('buyer_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('bid_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bid_round_id', sa.Integer(), nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('lines_parsed', sa.Integer(), nullable=True),
    sa.Column('lines_matched', sa.Integer(), nullable=True),
    sa.Column('lines_exception', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['bid_round_id'], ['bid_rounds.id'], ),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bid_files_id'), 'bid_files', ['id'], unique=False)
    op.create_table('master_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bid_round_id', sa.Integer(), nullable=False),
    sa.Column('part_number', sa.String(), nullable=False),
    sa.Column('part_number_normalized', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('manufacturer', sa.String(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('reserve_price', sa.Float(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('row_number', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['bid_round_id'], ['bid_rounds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_master_items_id'), 'master_items', ['id'], unique=False)
    op.create_index(op.f('ix_master_items_part_number'), 'master_items', ['part_number'], unique=False)
    op.create_index(op.f('ix_master_items_part_number_normalized'), 'master_items', ['part_number_normalized'], unique=False)
    op.create_table('bid_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bid_file_id', sa.Integer(), nullable=False),
    sa.Column('bid_round_id', sa.Integer(), nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=False),
    sa.Column('master_item_id', sa.Integer(), nullable=True),
    sa.Column('raw_part_number', sa.String(), nullable=False),
    sa.Column('normalized_part_number', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('total_price', sa.Float(), nullable=True),
    sa.Column('match_method', sa.String(), nullable=True),
    sa.Column('match_score', sa.Float(), nullable=True),
    sa.Column('match_status', sa.String(), nullable=True),
    sa.Column('exception_type', sa.String(), nullable=True),
    sa.Column('exception_notes', sa.Text(), nullable=True),
    sa.Column('exception_resolved', sa.Boolean(), nullable=True),
    sa.Column('exception_resolved_by', sa.String(), nullable=True),
    sa.Column('is_winner', sa.Boolean(), nullable=True),
    sa.Column('real_winning_price', sa.Float(), nullable=True),
    sa.Column('fluffed_loss_price', sa.Float(), nullable=True),
    sa.Column('z_score', sa.Float(), nullable=True),
    sa.Column('is_anomaly', sa.Boolean(), nullable=True),
    sa.Column('row_number', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['bid_file_id'], ['bid_files.id'], ),
    sa.ForeignKeyConstraint(['bid_round_id'], ['bid_rounds.id'], ),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['master_item_id'], ['master_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bid_lines_id'), 'bid_lines', ['id'], unique=False)
    op.create_table('deals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bid_round_id', sa.Integer(), nullable=False),
    sa.Column('master_item_id', sa.Integer(), nullable=False),
    sa.Column('winning_buyer_id', sa.Integer(), nullable=False),
    sa.Column('winning_bid_line_id', sa.Integer(), nullable=False),
    sa.Column('part_number', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('winning_price', sa.Float(), nullable=False),
    sa.Column('total_value', sa.Float(), nullable=False),
    sa.Column('razor_deal_id', sa.String(), nullable=True),
    sa.Column('razor_pushed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('razor_push_status', sa.String(), nullable=True),
    sa.Column('approved_by', sa.String(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['bid_round_id'], ['bid_rounds.id'], ),
    sa.ForeignKeyConstraint(['master_item_id'], ['master_items.id'], ),
    sa.ForeignKeyConstraint(['winning_bid_line_id'], ['bid_lines.id'], ),
    sa.ForeignKeyConstraint(['winning_buyer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deals_id'), 'deals', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_deals_id'), table_name='deals')
    op.drop_table('deals')
    op.drop_index(op.f('ix_bid_lines_id'), table_name='bid_lines')
    op.drop_table('bid_lines')
    op.drop_index(op.f('ix_master_items_part_number_normalized'), table_name='master_items')
    op.drop_index(op.f('ix_master_items_part_number'), table_name='master_items')
    op.drop_index(op.f('ix_master_items_id'), table_name='master_items')
    op.drop_table('master_items')
    op.drop_index(op.f('ix_bid_files_id'), table_name='bid_files')
    op.drop_table('bid_files')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_bid_rounds_id'), table_name='bid_rounds')
    op.drop_table('bid_rounds')
    # ### end Alembic commands ###
